[package]
authors = ["Walther Chen <walther.chen@gmail.com>"]
name = "beetl-macros"
version = "0.1.0"

[lib]
proc-macro = true

[dependencies]
quote = "0.3.15"

[dependencies.syn]
version = "0.11.11"
features = ["full"]
