[package]
authors = ["Walther Chen <walther.chen@gmail.com>"]
name = "beetl-macros"
version = "0.2.0"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = "1.0"
